name: Lab 8 CI/CD Workflow
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Verify Service
        run: echo "Successfully triggered Terraform to start the MongoDB service."
